name: Validate integration with hassfest

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v5"
        - uses: "home-assistant/actions/hassfest@master"